### PR TITLE
Updating unmute command + fixed a bug

### PR DESCRIPTION
**Pull request by malbouy**

### CODE REVIEW

**Comment by Tomato6966** [comment]
what did you fix?

**Comment by malbouy** [comment]
> what did you fix?
1. Sync invites button refused to work, fixed that
2. Unmute command did not remove the user from timeout and an admin/mod had to manually do that earlier (mute command not just adds role but also timeouts the user). So I changed it a bit to remove the user from timeout and remove the role as well.

**Comment by malbouy** [comment]
Any updates

**Comment by jedddg** [comment]
@Tomato6966 check this

**Comment by malbouy** [comment]
Ok no updates I guess, should I close?

**Comment by j0nibaer** [comment]
17 days later .-.

**Comment by Tomato6966** [comment]
Im not updating anything on this repo.

**Pull request closed without merging**
