### PR TITLE
Fix some bugs, deprecation warnings and useless code

### PR DESCRIPTION
**Pull request by jedd0888**
Title says it all

### CODE REVIEW

**Comment by jedd0888** [comment]
i forgot to turn my formatter off so let me explain better

> line 105 on sync-invites.js, you said greyuce??? i changed it to reduce
> setup-welcome, you used a ternary operator to change the value of the menu option where u can disable or enable dms on join, but not for the emoji, so i did it for that too

and yeah the rest is just fixing deprecations

**Comment by Tomato6966** [comment]
thanks for fixxing those "HUGE" (jk, minor) bugs

**Comment by brainiacv** [comment]
I helped you with that, but lmfao I forgot to submit pr

**Comment by jedd0888** [comment]
> I helped you with that, but lmfao I forgot to submit pr , venom here

Hahahaha ya
It was only comitted coz i wanted to make other changes

**Pull request merged**
