### PR TITLE
Added dotenv Module Many People Faced This Issue Even Me Also

### PR DESCRIPTION
**Pull request by NotZenixy**
That Module Is not found Some People Don't Know How to do it.So Its Fixed!!!

### CODE REVIEW

**Comment by jedddg** [comment]
It is easy for people to install this module. This seems more like a useless PR then a useful one.

**Comment by ImS3an** [comment]
yeah just do npm i dotenv ._.

**Comment by NotZenixy** [comment]
> It is easy for people to install this module. This seems more like a useless PR then a useful one.

Ya I know i just told u guys if u put the module it will be easy for noob guys i am saying u bcz the users can avoid asking coding help like module not found how to fix it we can avoid this thats why i told i know if u accept this pull request u i will contributed in this code otherwise u will add it ik

**Comment by NotZenixy** [comment]
> yeah just do npm i dotenv ._.

Ya I know i just told u guys if u put the module it will be easy for noob guys i am saying u bcz the users can avoid asking coding help like module not found how to fix it we can avoid this thats why i told i know if u accept this pull request u i will contributed in this code otherwise u will add it ik

**Comment by NotZenixy** [comment]
> 

if u can add it otherwise leave i know u dont want to me contributed in this code bcz i am a random person right??
U are genious 💪

**Comment by NotZenixy** [comment]
> It is easy for people to install this module. This seems more like a useless PR then a useful one.

> if u can add it otherwise leave i know u dont want to me contributed in this code bcz i am a random person right??
U are genious 💪

**Comment by jedddg** [comment]
That's fine, but maybe it would be more helpful to make an issue to say to add that as a dependency so Tomato can add this to a newer release

**Comment by NotZenixy** [comment]
> That's fine, but maybe it would be more helpful to make an issue to say to add that as a dependency so Tomato can add this to a newer release

Hm

**Review by SpaceDevelopmentDC — APPROVED** [review]

**Review by Bohaska — APPROVED** [review]

**Pull request merged**
