### PR TITLE
bot owner can access the hosting terminal in discord

### PR DESCRIPTION
**Pull request by opLUCIFERop**

### CODE REVIEW

**Review by jedddg — COMMENTED** [review]
First of all - this code doesn't have a correct description.
Second of all, there is a random user ID, and must be the first user id from the ownerIDS array as a suggestion.
Third of all, you are using a parameter that is deprecated, the code parameter.

Clearly, you used all the code from : https://www.youtube.com/watch?v=bUYkCBEa5Qk without proof-checking it. I do not think this should be merged.

**Comment by jedddg** [comment]
Also this is a massive security vulnerability

**Comment by Ruzie** [comment]
This code doesn't check does will it send buffer data or string, passing buffer through this endpoint to Discord may cause the bot to hang on `messageCreate` event or crash.

**Comment by Ruzie** [comment]
I also noticed that you've used var to declare a variable, using var was marked as deprecated in node v12 and above. var will not be removed from the node but you recommend not to use it as a var can be redeclared and the var type doesn't matter what you'll redefine.

**Comment by Tomato6966** [comment]
not adding it, experienced users can do it with !eval

```
!eval const cp = require("child_process");
cp.exec("mkdir /home/testDir");
```

**Pull request closed without merging**
