### PR TITLE
Added Token env and config.json support

### PR DESCRIPTION
**Pull request by NotEnd035**
put `token=YOUR_BOT_TOKEN` in a .env file to Make your token Safe

### CODE REVIEW

**Comment by omxpro** [comment]
Yes!!!

**Comment by jedd0888** [comment]
what about people who aren't using replit and have an actual .env file?
it would have been useful if you could have added a line defining the dotenv config

**Comment by Tomato6966** [comment]
There is a .env support

**Comment by Tomato6966** [comment]
I just accidentally removed it i will add it soon back

**Pull request closed without merging**
