### PR TITLE
Bug fixes+changes

### PR DESCRIPTION
**Pull request by jedddg**
If you would like to use owner commands like `detailedeval,eval,deployslash`, instead of going to the commands and changing Tomato's ID, it will use the first owner ID in the array in config.json, to decide whether the user is allowed to run the command or not

it was a simple change but bcoz i saw someone made an issue on it i thought it would have been useful to add this

Also fixed setup-boostlog (hopefully, coz i cant test it)

and i did more stuff but i am not bothered to explain, just read the commit messages lol

### CODE REVIEW

**Comment by testbot-github** [comment]
@Tomato6966

**Review by aziz191546 — COMMENTED** [review]
Reason:  ReferenceError: guild is not defined
    at first_layer (/home/****/***/commands/👑 Owner/setup-serverlog.js:41:46)
    at Object.run (/home/****/****/commands/👑 Owner/setup-serverlog.js:37:9)
    at module.exports (/home/****/****/events/guild/messageCreate.js:295:17)
    at Client.emit (node:events:402:35)
    at MessageCreateAction.handle (/home/****/****/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/***/*****/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/****/****/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/****/****/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/****/****/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/****/****/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/****/****/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/****/****/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.socketOnData (/home/****/****/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (node:events:390:28)

**Comment by jedd0888** [comment]
> Reason: ReferenceError: guild is not defined at first_layer (/home/__**/**_/commands/👑 Owner/setup-serverlog.js:41:46) at Object.run (/home/__**/**__/commands/👑 Owner/setup-serverlog.js:37:9) at module.exports (/home/__**/**__/events/guild/messageCreate.js:295:17) at Client.emit (node:events:402:35) at MessageCreateAction.handle (/home/__**/**__/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14) at Object.module.exports [as MESSAGE_CREATE] (/home/_**/*****/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32) at WebSocketManager.handlePacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31) at WebSocketShard.onPacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22) at WebSocketShard.onMessage (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10) at WebSocket.onMessage (/home/****/****/node_modules/ws/lib/event-target.js:199:18) at WebSocket.emit (node:events:390:28) at Receiver.receiverOnMessage (/home/****/****/node_modules/ws/lib/websocket.js:1098:20) at Receiver.emit (node:events:390:28) at Receiver.dataMessage (/home/****/****/node_modules/ws/lib/receiver.js:528:14) at Receiver.getData (/home/****/****/node_modules/ws/lib/receiver.js:446:17) at Receiver.startLoop (/home/****/****/node_modules/ws/lib/receiver.js:148:22) at Receiver._write (/home/****/****/node_modules/ws/lib/receiver.js:83:10) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Receiver.Writable.write (node:internal/streams/writable:334:10) at TLSSocket.socketOnData (/home/****/****/node_modules/ws/lib/websocket.js:1192:35) at TLSSocket.emit (node:events:390:28)

How did you get access to that setup-serverlog command?
That was accidentally added by me i was testing something, and its deleted now

**Comment by itzhy22** [comment]
> > Reason: ReferenceError: guild is not defined at first_layer (/home/****/**_/commands/👑 Owner/setup-serverlog.js:41:46) at Object.run (/home/****/****/commands/👑 Owner/setup-serverlog.js:37:9) at module.exports (/home/****/****/events/guild/messageCreate.js:295:17) at Client.emit (node:events:402:35) at MessageCreateAction.handle (/home/****/**__/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14) at Object.module.exports [as MESSAGE_CREATE] (/home/_**/*****/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32) at WebSocketManager.handlePacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31) at WebSocketShard.onPacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22) at WebSocketShard.onMessage (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10) at WebSocket.onMessage (/home/****/****/node_modules/ws/lib/event-target.js:199:18) at WebSocket.emit (node:events:390:28) at Receiver.receiverOnMessage (/home/****/****/node_modules/ws/lib/websocket.js:1098:20) at Receiver.emit (node:events:390:28) at Receiver.dataMessage (/home/****/****/node_modules/ws/lib/receiver.js:528:14) at Receiver.getData (/home/****/****/node_modules/ws/lib/receiver.js:446:17) at Receiver.startLoop (/home/****/****/node_modules/ws/lib/receiver.js:148:22) at Receiver._write (/home/****/****/node_modules/ws/lib/receiver.js:83:10) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Receiver.Writable.write (node:internal/streams/writable:334:10) at TLSSocket.socketOnData (/home/****/****/node_modules/ws/lib/websocket.js:1192:35) at TLSSocket.emit (node:events:390:28)
> 
> How did you get access to that setup-serverlog command? That was accidentally added by me i was testing something, and its deleted now image

its not deleted 
image

**Comment by jedd0888** [comment]
> > > Reason: ReferenceError: guild is not defined at first_layer (/home/****/**_/commands/👑 Owner/setup-serverlog.js:41:46) at Object.run (/home/****/****/commands/👑 Owner/setup-serverlog.js:37:9) at module.exports (/home/****/****/events/guild/messageCreate.js:295:17) at Client.emit (node:events:402:35) at MessageCreateAction.handle (/home/****/**__/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14) at Object.module.exports [as MESSAGE_CREATE] (/home/_**/*****/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32) at WebSocketManager.handlePacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31) at WebSocketShard.onPacket (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22) at WebSocketShard.onMessage (/home/****/****/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10) at WebSocket.onMessage (/home/****/****/node_modules/ws/lib/event-target.js:199:18) at WebSocket.emit (node:events:390:28) at Receiver.receiverOnMessage (/home/****/****/node_modules/ws/lib/websocket.js:1098:20) at Receiver.emit (node:events:390:28) at Receiver.dataMessage (/home/****/****/node_modules/ws/lib/receiver.js:528:14) at Receiver.getData (/home/****/****/node_modules/ws/lib/receiver.js:446:17) at Receiver.startLoop (/home/****/****/node_modules/ws/lib/receiver.js:148:22) at Receiver._write (/home/****/****/node_modules/ws/lib/receiver.js:83:10) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Receiver.Writable.write (node:internal/streams/writable:334:10) at TLSSocket.socketOnData (/home/****/****/node_modules/ws/lib/websocket.js:1192:35) at TLSSocket.emit (node:events:390:28)
> 
> > 
> 
> > How did you get access to that setup-serverlog command? That was accidentally added by me i was testing something, and its deleted now image
> 
> 
> 
> its not deleted 
> 
> image
> 
> 

Check my branch, it is

**Comment by Tomato6966** [comment]
I already fixxed all of those bugs before in the script.
*except the typos*

aka i will upload them in the next major update `v11.0`

When i finished the [Sharded Version with MONGODB SUPPORT](https://github.com/Tomato6966/Multipurpose-discord-bot/tree/sharded_with_mongo)

**Comment by Tomato6966** [comment]
But thanks for your effort jedd!

**Comment by Tomato6966** [comment]
If u want fixxes, tell them to me on discord

**Comment by Tomato6966** [comment]
imma keep it open, so i dont forget!

**Comment by jedd0888** [comment]
okay

**Comment by riciuuu** [comment]
> I already fixxed all of those bugs before in the script. _except the typos_
> 
> aka i will upload them in the next major update `v11.0`
> 
> When i finished the [Sharded Version with MONGODB SUPPORT](https://github.com/Tomato6966/Multipurpose-discord-bot/tree/sharded_with_mongo)

when will this version be ready?

**Comment by chiqors** [comment]
> okay

@jedddg  The fixes has been put on tomato's main branch?

**Comment by jedddg** [comment]
these changes have not been made yet.

* the fatal boostlog bug still occurs
* owner commands require going into the commands and configuring it custom

**Pull request closed without merging**
